In [ ]:
1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [1]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)

# Interchange rows and columns (transpose the array)
transposed_array = array.T
print("\nTransposed Array:")
print(transposed_array)

Original Array:
[[ 6 24 59]
 [74 46 29]
 [99 32 10]]

Transposed Array:
[[ 6 74 99]
 [24 46 32]
 [59 29 10]]


In [2]:
import numpy as np

# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)  # This will create an array with values from 0 to 9
print("Original 1D Array:")
print(array_1d)

# Reshape into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped into 2x5 Array:")
print(array_2x5)

# Reshape into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped into 5x2 Array:")
print(array_5x2)

Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped into 2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped into 5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [3]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array_4x4)

# Add a border of zeros around the 4x4 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with a Border of Zeros:")
print(array_6x6)

Original 4x4 Array:
[[0.46223724 0.21104515 0.74860271 0.47028067]
 [0.41520104 0.57729669 0.05461814 0.08690795]
 [0.32160549 0.3229018  0.58230873 0.4829655 ]
 [0.76939751 0.90344994 0.45915131 0.30753739]]

6x6 Array with a Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.46223724 0.21104515 0.74860271 0.47028067 0.        ]
 [0.         0.41520104 0.57729669 0.05461814 0.08690795 0.        ]
 [0.         0.32160549 0.3229018  0.58230873 0.4829655  0.        ]
 [0.         0.76939751 0.90344994 0.45915131 0.30753739 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print("Array of integers from 10 to 60 with a step of 5:")
print(array)

Array of integers from 10 to 60 with a step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [5]:
import numpy as np

# Create a NumPy array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(array)
lowercase = np.char.lower(array)
titlecase = np.char.title(array)
capitalize = np.char.capitalize(array)

# Display the results
print("Original Array:")
print(array)
print("\nUppercase:")
print(uppercase)
print("\nLowercase:")
print(lowercase)
print("\nTitle Case:")
print(titlecase)
print("\nCapitalized:")
print(capitalize)

Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


In [6]:
import numpy as np

# Create a NumPy array of words
words = np.array(['python', 'numpy', 'pandas'])

# Insert a space between each character of every word
spaced_words = np.char.join(' ', words)

# Display the results
print("Original Array of Words:")
print(words)
print("\nWords with Spaces Between Characters:")
print(spaced_words)

Original Array of Words:
['python' 'numpy' 'pandas']

Words with Spaces Between Characters:
['p y t h o n' 'n u m p y' 'p a n d a s']


In [7]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Perform element-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

# Display the results
print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [8]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [9]:
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)
print("Array of Random Integers:")
print(random_integers)

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("\nPrime Numbers in the Array:")
print(prime_numbers)

Array of Random Integers:
[765 422 850 916 642 532 319 473 370 335  47 482 420 608 378 909 800 112
 553 806 919 288 220 968 168 506 970 640 807 545 322 763 757 960 347 239
 989 641 471  54 333 622 365  86 698 965 182 851 920  95 498 307 784 221
 487  25 102   6 261 539 352 357   9 212  98 265 154 195 518 172 386 881
 317 840 581 358 811 870 545 604 690 701 737 569 651 950 580 379 960 140
 927  53 239 690 934 198   5 499 901  56]

Prime Numbers in the Array:
[47, 919, 757, 347, 239, 641, 307, 487, 881, 317, 811, 701, 569, 379, 53, 239, 5, 499]


In [11]:
import numpy as np

# Create a NumPy array representing daily temperatures for a month (30 days)
# For example, let's use random temperatures between 0 and 30 degrees Celsius
daily_temperatures = np.random.uniform(0, 30, size=30)
print("Daily Temperatures for the Month:")
print(daily_temperatures)

# Reshape the array into weeks (4 complete weeks and 2 extra days)
# This will give us 4 rows for the first 28 days, and the last row will contain the last 2 days
weekly_temperatures = np.zeros((5, 7))
weekly_temperatures[:4, :7] = daily_temperatures[:28].reshape(4, 7)
weekly_temperatures[4, :2] = daily_temperatures[28:]

# Calculate weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("\nWeekly Averages:")
print(weekly_averages)

Daily Temperatures for the Month:
[12.74632708  1.33625738  3.21877159 12.76919559 27.69994434 27.56111218
 24.91400936  9.49808194 28.4071341  28.63751208 23.78135482 10.84521151
 13.5376395  24.80013173 26.93871356 26.97092004  2.46735588  5.33227666
 23.00289826 22.17797305  3.78671691  8.17516049 20.90633017 12.43249273
  9.46511563  1.20035772  3.53819468  2.42618    26.64138665 16.55841728]

Weekly Averages:
[15.74937393 19.92958081 15.81097919  8.30626163  6.17140056]
