In [ ]:
### Theoretical Questions ###

In [ ]:
1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In [ ]:
Answer1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?

In [ ]:
NumPy, short for Numerical Python, is a fundamental library for scientific computing and data analysis in Python. It enhances Python's capabilities for numerical operations in several key ways:

Purpose of NumPy:-

1. Efficient Array Storage: NumPy introduces the ndarray (n-dimensional array) object, which is a fast, flexible container for large datasets in Python. Unlike Python lists, which can store heterogeneous data types, NumPy arrays are homogeneous, enabling efficient memory use and performance.
2. Numerical Operations: NumPy provides a wide range of mathematical functions for array operations, including element-wise arithmetic, statistical operations, linear algebra, and more, allowing for complex calculations with ease.
3. Integration with Other Libraries: Many other scientific libraries in Python (such as SciPy, Pandas, and Matplotlib) are built on top of NumPy, making it a foundational tool in the scientific computing ecosystem.

Advantages of NumPy:-

1. Performance: NumPy's array operations are implemented in C, allowing them to be significantly faster than equivalent operations using Python lists. Vectorization, or performing operations on entire arrays without explicit loops, further boosts performance.
2. Convenient Syntax: NumPy provides a rich set of functions and syntax for array manipulation, making it easier to write clear and concise code. This includes slicing, broadcasting, and reshaping arrays.
3. Broadcasting: This feature allows operations between arrays of different shapes, enabling efficient computation without the need for explicit replication of data. For example, adding a scalar to an array adds the scalar to each element of the array.
4. Multidimensional Support: NumPy supports multi-dimensional arrays, making it easier to work with matrices and tensors, which are common in scientific computing and machine learning.
5. Comprehensive Functionality: It includes functions for mathematical operations (like trigonometric and statistical functions), linear algebra (like matrix operations), and random number generation, making it suitable for a wide range of applications.
6. Interoperability: NumPy arrays can be easily integrated with other libraries and tools, including data visualization libraries like Matplotlib, making it simple to create plots and graphs from data stored in NumPy arrays.

Conclusion:-
     In summary, NumPy significantly enhances Python's capabilities for numerical operations, providing efficient, powerful tools for scientific computing and data analysis. Its performance, ease of use, and extensive functionality make it an indispensable resource for researchers, engineers, and data scientists.

In [ ]:
Answer2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

In [ ]:
The np.mean() and np.average() functions in NumPy are both used to compute averages, but they have distinct features and use cases. Here's a comparison of the two:

np.mean()
* Purpose: Computes the arithmetic mean of the elements in an array.
* Syntax: np.mean(a, axis=None, dtype=None, out=None)
* Parameters:
# a: Input array.
# axis: Axis along which to compute the mean. Default is None, meaning the mean is computed over the entire array.
# dtype: Data type to use for the result.
# out: Optional output array to place the result.
* Return Value: The mean of the array elements.

np.average()
* Purpose: Computes a weighted average of the elements in an array.
* Syntax: np.average(a, axis=None, weights=None, returned=False)
* Parameters:
# a: Input array.
# axis: Axis along which to compute the average.
# weights: Optional array of weights. If provided, the average is computed as the sum of the weights multiplied by the values divided by the sum of the weights.
# returned: If True, returns a tuple (average, sum of weights).
* Return Value: The weighted average if weights are provided; otherwise, it behaves like np.mean().

Key Differences:-
1. Weighting:
* np.mean() computes a simple arithmetic mean, treating all elements equally.
* np.average() allows for weighting of elements, giving flexibility in cases where some elements should contribute more than others to the final average.
2. Functionality:
* np.mean() is straightforward and faster for simple mean calculations.
* np.average() provides more functionality with its weights parameter, making it more versatile when dealing with weighted data.

When to Use Which
1. Use np.mean() when:
* You need a simple average of all elements in an array.
* You are dealing with homogeneous data without special weights.
2. Use np.average() when:
* You need to compute a weighted average, where certain values should have more influence on the result.
* You require the additional output of the sum of weights along with the average.

In [4]:
import numpy as np

data = np.array([1, 2, 3, 4])

# Using np.mean
mean_value = np.mean(data)  # Output: 2.5

# Using np.average without weights
average_value = np.average(data)  # Output: 2.5

# Using np.average with weights
weights = np.array([1, 2, 3, 4])
weighted_average = np.average(data, weights=weights)  # Output: 3.0

In [ ]:
Answer3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [ ]:
Reversing a NumPy array can be done easily using slicing. Here are methods for reversing both 1D and 2D arrays along different axes:

Reversing a 1D Array
For a 1D array, you can reverse the array using slicing with [::-1].

In [5]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5])

# Reverse the 1D array
reversed_1d = array_1d[::-1]

print("Original 1D array:", array_1d)
print("Reversed 1D array:", reversed_1d)

Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]


In [ ]:
Reversing a 2D Array
For a 2D array, you can reverse it along different axes using slicing.
1. Reverse along axis 0 (rows): This will reverse the rows of the array.

In [6]:
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Reverse along axis 0 (rows)
reversed_axis0 = array_2d[::-1, :]

print("Original 2D array:\n", array_2d)
print("Reversed along axis 0 (rows):\n", reversed_axis0)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed along axis 0 (rows):
 [[7 8 9]
 [4 5 6]
 [1 2 3]]


In [ ]:
2. Reverse along axis 1 (columns): This will reverse the columns of the array.

In [7]:
# Reverse along axis 1 (columns)
reversed_axis1 = array_2d[:, ::-1]

print("Reversed along axis 1 (columns):\n", reversed_axis1)

Reversed along axis 1 (columns):
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [ ]:
Summary of the Methods
* 1D Array: Use slicing [::-1] to reverse the array.
* 2D Array:
   . To reverse rows, use [::-1, :].
   . To reverse columns, use [:, ::-1].

These methods are efficient and leverage NumPy's powerful slicing capabilities to easily reverse arrays along specified axes.

In [ ]:
Answer4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

In [ ]:
In NumPy, we can determine the data type of the elements in an array using the .dtype attribute. This attribute provides information about the type of data stored in the array, such as whether it’s an integer, float, string, etc.

Determining Data Type
Here’s how to check the data type of a NumPy array:

In [8]:
import numpy as np

# Create an array
array = np.array([1, 2, 3], dtype=np.int32)

# Determine the data type
data_type = array.dtype

print("Data type of the array:", data_type)

Data type of the array: int32


In [ ]:
Importance of Data Types
1. Memory Management:
* Different data types consume different amounts of memory. For instance, an int32 takes up 4 bytes, while an int64 takes up 8 bytes. Using the appropriate data type can significantly reduce the memory footprint of large datasets.
* This is particularly important when dealing with large arrays in scientific computing, where memory can become a limiting factor.

2.Performance:
* Operations on arrays of smaller data types (like float32 vs. float64) can be faster due to lower memory bandwidth requirements.
* Smaller data types can improve cache efficiency and reduce the time taken for computations, especially in vectorized operations.

3.Type Safety:
* Specifying the correct data type helps prevent errors in calculations. For example, using integer data types for integer values can prevent unexpected behaviors when performing mathematical operations.
* Type mismatches can lead to silent errors or unintended data conversion, affecting the integrity of calculations.

4. Compatibility with Libraries:
* Many scientific libraries that build on NumPy (like SciPy, Pandas, and TensorFlow) often expect specific data types for optimal performance and compatibility. Understanding and using the right types ensures better interoperability between libraries.

Conclusion:-
     Understanding and managing data types in NumPy is crucial for efficient memory usage and performance optimization in scientific computing and data analysis. By leveraging the appropriate data types, you can ensure that your code runs efficiently while minimizing memory consumption.

In [ ]:
Answer5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [ ]:
In NumPy, ndarrays (n-dimensional arrays) are the core data structure used for storing and manipulating large datasets efficiently. They provide a powerful way to work with numerical data, offering many advantages over standard Python lists.

Key Features of ndarrays
1. Homogeneous Data:
* All elements in an ndarray are of the same data type (e.g., all integers or all floats), which allows for efficient memory usage and performance optimization.
2. Multidimensional:
* Ndarrays can be one-dimensional (1D), two-dimensional (2D), or n-dimensional, making them versatile for various applications, such as matrices and tensors.
3. Contiguous Memory:
* Ndarrays store data in contiguous blocks of memory, which enhances performance for numerical computations and allows for efficient access patterns.
4. Vectorized Operations:
* Operations on ndarrays can be performed element-wise without explicit loops, enabling concise and efficient computations. This feature is known as vectorization.
5. Broadcasting:
* Ndarrays support broadcasting, allowing operations between arrays of different shapes without requiring explicit replication of data, which simplifies code and improves performance.
6. Rich Functionality:
* NumPy provides a wide array of functions for mathematical operations, statistical analysis, linear algebra, and more, all optimized for use with ndarrays.
7. Indexing and Slicing:
* Ndarrays support advanced indexing and slicing techniques, allowing for flexible and efficient data manipulation.

Differences from Standard Python Lists
1. Data Type:
* ndarrays: Homogeneous (all elements are of the same type).
* Lists: Heterogeneous (elements can be of different types), which can lead to inefficiencies.
2. Performance:
* ndarrays: More efficient for numerical operations due to contiguous memory and vectorization.
* Lists: Slower for numerical computations since they do not support vectorized operations and require iterating through elements.
3. Memory Consumption:
* ndarrays: More memory-efficient for large datasets because of their homogeneous nature and optimized storage.
* Lists: Higher memory overhead due to the need to store type information for each element.
4. Functionality:
* ndarrays: Equipped with a wide range of built-in mathematical functions and operations optimized for performance.
* Lists: Limited in terms of mathematical operations; you would typically need to use loops or list comprehensions for computations.
5. Dimensionality:
* ndarrays: Can easily handle multiple dimensions (2D, 3D, etc.).
* Lists: While you can create nested lists for multi-dimensional data, they are less efficient and more cumbersome to manipulate.

Example Comparison
Using a List:

In [9]:
# Creating a list
list_data = [1, 2, 3, 4]

# Summing elements using a loop
list_sum = sum(list_data)  # Output: 10

In [ ]:
Using an ndarray:

In [10]:
import numpy as np

# Creating an ndarray
array_data = np.array([1, 2, 3, 4])

# Summing elements using NumPy
array_sum = np.sum(array_data)  # Output: 10

In [ ]:
Conclusion
     Ndarrays in NumPy are powerful, efficient, and designed for numerical computing. They provide significant advantages over standard Python lists, particularly in performance, memory usage, and functionality, making them essential for scientific computing and data analysis tasks.

In [ ]:
Answer6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

In [ ]:
NumPy arrays provide significant performance benefits over Python lists, especially when it comes to large-scale numerical operations. Here are some key aspects of their performance advantages:

1. Memory Efficiency
* Contiguous Memory Allocation: NumPy arrays are stored in contiguous memory blocks, which minimizes overhead and allows for faster access times. In contrast, Python lists are made up of pointers to objects, which leads to more fragmented memory and higher overhead.
* Homogeneous Data Types: Ndarrays store data of the same type, enabling NumPy to use a more compact memory representation. Python lists, being heterogeneous, must store type information for each element, increasing memory usage.
2. Speed of Operations
* Vectorization: NumPy allows for vectorized operations, meaning you can perform operations on entire arrays without explicit loops. This is achieved through underlying C and Fortran implementations, which are optimized for performance.
. Example: Adding two large arrays element-wise is significantly faster in NumPy than using a Python loop to iterate through each element.
* Compiled Code: Many of NumPy's operations are implemented in low-level languages like C, which are faster than Python code. This allows for optimizations that reduce the time complexity of operations.
3. Reduced Function Call Overhead
* When using NumPy, operations are applied to entire arrays or slices rather than individual elements. This reduces the overhead of Python function calls, which can become a bottleneck when dealing with large datasets.
4. Efficient Use of Mathematical Libraries
* NumPy can leverage highly optimized libraries like BLAS and LAPACK for linear algebra operations, which can be several times faster than Python-based implementations.
* These libraries are often multi-threaded, making them capable of utilizing multiple CPU cores for operations, further enhancing performance.
5. Broadcasting
* NumPy's broadcasting mechanism allows operations between arrays of different shapes without needing to manually replicate data. This not only saves memory but also speeds up calculations by eliminating the need for extra loops and memory allocation.
6. Indexing and Slicing
* NumPy provides advanced indexing and slicing capabilities, allowing for more efficient data access and manipulation. Operations that require accessing subarrays or performing conditional selections are optimized in NumPy, resulting in better performance compared to traditional Python lists.
7. Parallel Processing
* While Python lists are inherently single-threaded, NumPy can take advantage of parallel processing through libraries like Dask or by leveraging multi-threaded operations within NumPy itself, especially for large data operations.

Example Performance Comparison
Here’s a simple demonstration comparing the performance of NumPy arrays versus Python lists for a large-scale operation:

In [11]:
import numpy as np
import time

# Large-scale operation with Python lists
list_size = 10**6
py_list = list(range(list_size))

# Timing the sum with a Python list
start_time = time.time()
list_sum = sum(py_list)
print("Sum using Python list:", list_sum)
print("Time taken (Python list):", time.time() - start_time)

# Large-scale operation with NumPy arrays
np_array = np.arange(list_size)

# Timing the sum with a NumPy array
start_time = time.time()
array_sum = np.sum(np_array)
print("Sum using NumPy array:", array_sum)
print("Time taken (NumPy array):", time.time() - start_time)

Sum using Python list: 499999500000
Time taken (Python list): 0.13400006294250488
Sum using NumPy array: 1783293664
Time taken (NumPy array): 0.004999876022338867


In [ ]:
Conclusion:-
     NumPy arrays provide substantial performance benefits over Python lists for large-scale numerical operations due to their efficient memory usage, speed of operations, reduced overhead, and the ability to leverage optimized libraries. These advantages make NumPy the go-to choice for scientific computing, data analysis, and any task requiring heavy numerical computations.

In [ ]:
Answer7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

In [ ]:
In NumPy, vstack() and hstack() are functions used to stack arrays vertically and horizontally, respectively. They are useful for combining multiple arrays along specified axes. Here’s a detailed comparison along with examples.

vstack()
* Function: Stacks arrays vertically (row-wise).
* Usage: Combines arrays along the first axis (axis=0).
* Requirements: The input arrays must have the same shape for all dimensions except for the first dimension.

In [12]:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Stack the arrays vertically
result_vstack = np.vstack((array1, array2))

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Result of vstack:\n", result_vstack)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Result of vstack:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
hstack()
* Function: Stacks arrays horizontally (column-wise).
* Usage: Combines arrays along the second axis (axis=1).
* Requirements: The input arrays must have the same number of rows (i.e., the same shape for all dimensions except the second).

In [13]:
# Stack the arrays horizontally
result_hstack = np.hstack((array1, array2))

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Result of hstack:\n", result_hstack)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Result of hstack:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [ ]:
Summary:-
* vstack(): Stacks arrays on top of each other (increasing the number of rows).
* hstack(): Stacks arrays side by side (increasing the number of columns).

   Both functions are useful for manipulating and organizing data in arrays, and they simplify the process of combining multiple arrays in a structured manner.

In [ ]:
Answer8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

In [ ]:
In NumPy, fliplr() and flipud() are functions used to reverse the order of elements in an array, but they operate along different axes and have distinct effects based on the dimensions of the array.

fliplr()
* Function: Flips an array left to right (i.e., reverses the order of columns).
* Usage: Primarily operates on 2D arrays, but can be applied to higher-dimensional arrays as well.
* Effect: Each row of the array is reversed.

In [14]:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Flip the array left to right
flipped_lr = np.fliplr(array_2d)

print("Original Array:\n", array_2d)
print("Flipped Left to Right:\n", flipped_lr)

Original Array:
 [[1 2 3]
 [4 5 6]]
Flipped Left to Right:
 [[3 2 1]
 [6 5 4]]


In [ ]:
flipud()
* Function: Flips an array up to down (i.e., reverses the order of rows).
* Usage: Primarily operates on 2D arrays but can also be applied to higher-dimensional arrays.
* Effect: Each column of the array is reversed.

In [15]:
# Flip the array up to down
flipped_ud = np.flipud(array_2d)

print("Original Array:\n", array_2d)
print("Flipped Up to Down:\n", flipped_ud)

Original Array:
 [[1 2 3]
 [4 5 6]]
Flipped Up to Down:
 [[4 5 6]
 [1 2 3]]


In [ ]:
Effects on Various Array Dimensions
* 1D Arrays: Both fliplr() and flipud() will have the same effect since there is no distinct left/right or up/down. They will simply reverse the order of elements.

In [16]:
array_1d = np.array([1, 2, 3])

flipped_lr_1d = np.fliplr(array_1d.reshape(1, -1))  # Needs to be 2D
flipped_ud_1d = np.flipud(array_1d.reshape(1, -1))  # Needs to be 2D

print("Flipped Left to Right (1D):", flipped_lr_1d)
print("Flipped Up to Down (1D):", flipped_ud_1d)

Flipped Left to Right (1D): [[3 2 1]]
Flipped Up to Down (1D): [[1 2 3]]


In [ ]:
* 2D Arrays: The functions behave as described above, flipping along their respective axes.
* Higher-Dimensional Arrays: Both functions will only affect the specified axes (last for fliplr() and first for flipud()). The remaining dimensions will remain unchanged.

Summary
* fliplr(): Reverses the order of elements in each row (left to right).
* flipud(): Reverses the order of elements in each column (up to down).

     These functions are useful for manipulating array data in various contexts, especially when working with matrices or image data where orientation is significant.

In [ ]:
Answer9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [ ]:
The array_split() method in NumPy is a powerful function used to split an array into multiple sub-arrays. This function is particularly useful for dividing large datasets into smaller chunks for easier processing or analysis.

Functionality of array_split()
1. Basic Usage:
* array_split() allows you to specify the number of equal (or nearly equal) parts you want to divide the input array into.
* It can handle arrays of any shape, including 1D, 2D, and higher-dimensional arrays.

2. Syntax:

In [ ]:
numpy.array_split(ary, indices_or_sections, axis=0)

In [ ]:
* ary: The input array to be split.
* indices_or_sections: The number of equal parts to split the array into, or specific indices at which to split the array.
* axis: The axis along which to split the array (default is 0).

Handling Uneven Splits
When the total size of the array is not perfectly divisible by the number of sections specified, array_split() handles this by distributing the remainder elements among the resulting sub-arrays.
* Example with Uneven Splits: If you try to split an array of size 10 into 3 parts, the output will be two arrays of size 3 and one array of size 4.

In [17]:
import numpy as np

# Create a 1D array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Split the array into 3 parts
result = np.array_split(array, 3)

print("Original Array:", array)
print("Split Array:", result)

Original Array: [ 1  2  3  4  5  6  7  8  9 10]
Split Array: [array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


In [ ]:
Key Points
* The resulting sub-arrays can have different sizes when the total number of elements is not evenly divisible by the specified number of sections.
* This behavior allows for flexibility in handling datasets of varying sizes without needing to manage the leftovers manually.

Additional Features
* Splitting Along a Specific Axis: For multi-dimensional arrays, you can specify the axis along which to split. For example, in a 2D array, you could split along rows or columns.

In [18]:
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]])

# Split the array into 3 parts along the first axis (rows)
result_2d = np.array_split(array_2d, 3, axis=0)

print("Original 2D Array:\n", array_2d)
print("Split 2D Array:\n", result_2d)

Original 2D Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Split 2D Array:
 [array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]]), array([[10, 11, 12]])]


In [ ]:
Conclusion:-
     The array_split() method in NumPy is a flexible and useful tool for splitting arrays into sub-arrays. Its ability to handle uneven splits makes it particularly valuable for working with datasets that do not divide evenly, allowing for efficient data manipulation and processing in various applications.

In [ ]:
Answer10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

In [ ]:
Vectorization and broadcasting are two key concepts in NumPy that enhance the efficiency and performance of array operations. Understanding these concepts is crucial for optimizing numerical computations in Python.

Vectorization:
Definition: Vectorization refers to the ability to perform operations on entire arrays (or large chunks of data) without the need for explicit loops. This is achieved by using NumPy’s built-in functions, which are implemented in optimized C or Fortran code. As a result, operations are performed at a much higher speed compared to traditional Python loops.

Benefits:
* Performance: By avoiding Python loops, vectorized operations minimize overhead, leading to significant speedups. NumPy functions are optimized for performance and utilize low-level programming to process data more efficiently.
* Conciseness: Vectorized code is often more concise and readable, making it easier to maintain and understand.

In [19]:
import numpy as np

# Create two large arrays
a = np.random.rand(1_000_000)
b = np.random.rand(1_000_000)

# Vectorized addition
c = a + b  # This performs the addition on all elements without explicit loops

In [ ]:
Broadcasting
Definition: Broadcasting is a powerful feature that allows NumPy to perform arithmetic operations on arrays of different shapes. When performing operations on two arrays, NumPy automatically expands the smaller array across the larger array, aligning their shapes for element-wise operations.

Rules of Broadcasting:
1. If the arrays have different numbers of dimensions, the smaller array is padded with ones on the left side until they have the same number of dimensions.
2. The sizes of the arrays are compared element-wise. If they are equal, or if one of them is 1, the arrays are considered compatible.
3. If the sizes are incompatible, a ValueError is raised.

Benefits:
* Flexibility: Broadcasting enables operations between arrays of different shapes without the need to manually reshape or replicate data.
* Memory Efficiency: Instead of creating multiple copies of the data to match the shapes, broadcasting allows NumPy to operate directly on the original data, saving memory.

In [20]:
# Create a 2D array and a 1D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
array_1d = np.array([10, 20, 30])

# Broadcasting the 1D array across the 2D array
result = array_2d + array_1d  # The 1D array is broadcast to match the shape of the 2D array

print("Original 2D Array:\n", array_2d)
print("1D Array:\n", array_1d)
print("Result after Broadcasting:\n", result)

Original 2D Array:
 [[1 2 3]
 [4 5 6]]
1D Array:
 [10 20 30]
Result after Broadcasting:
 [[11 22 33]
 [14 25 36]]


In [ ]:
Conclusion:-
     Both vectorization and broadcasting significantly contribute to efficient array operations in NumPy:
* Vectorization allows you to perform operations on entire arrays at once, speeding up computations and making code cleaner.
* Broadcasting enables seamless arithmetic operations on arrays of different shapes, enhancing flexibility and memory efficiency.

   Together, these concepts are fundamental for achieving high performance in numerical computing and data analysis, allowing for concise and efficient code in scientific and analytical applications.